title: R for modellers
logo: /assets/img/vibrio-cholerae.jpeg
description: Information about the use of the R programming language, with focus on stuff useful to mathematical modellers.
show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-1943806-8
plugins:
  - jekyll-sitemap
