---
vignette-nb: "01"
title: Introduction to and installation of R
long-title: Vignette 01 - Introduction to and installation of R
description-meta: Julien Arino - R for modellers - Vignette 01 - Introduction to and installation of R
author: Julien Arino
institute: University of Manitoba*
format: 
  revealjs:
    theme: night    
    template-partials:
      - title-slide.html
    toc: true
    toc-depth: 1
    toc-title: Outline
    auto-stretch: true
    progress: false
    preview-links: true
    code-line-numbers: false
    chalkboard: true
---

# Foreword: the R language {.r-fit-text}

---

## [R was originally for stats but is now much more]{.r-fit-text}

- Open source version of S
- Appeared in 1993
- Now (2024-03) version 4.3

```{.r}
> install.packages("rversions")
> library(rversions)
> tail(r_versions())
    version                date              nickname
129   4.2.2 2022-10-31 08:05:54 Innocent and Trusting
130   4.2.3 2023-03-15 08:06:01      Shortstop Beagle
131   4.3.0 2023-04-21 07:06:14      Already Tomorrow
132   4.3.1 2023-06-16 07:06:07         Beagle Scouts
133   4.3.2 2023-10-31 08:07:42             Eye Holes
134   4.3.3 2024-02-29 08:07:53       Angel Food Cake
```

## [R uses a lot of code from other languages]{.r-fit-text}

- One major advantage in my view: uses a lot of C and Fortran code. E.g., `deSolve`:

> The functions provide an interface to the FORTRAN functions 'lsoda', 'lsodar', 'lsode', 'lsodes' of the 'ODEPACK' collection, to the FORTRAN functions 'dvode', 'zvode' and 'daspk' and a C-implementation of solvers of the 'Runge-Kutta' family with fixed or variable time steps

## Lots of people use R

- Very active community on the web, easy to find solutions (same true of Python, I just prefer R)

## R is a scripted language

- Interactive
- Allows you to work in real time
    - Be careful: what is in memory might involve steps not written down in a script
    - If you want to reproduce your steps, it is good to write all the steps down in a script and to test from time to time running using `Rscript`: this will ensure that all that is required to run is indeed loaded to memory when it needs to, i.e., that it is not already there..

## Similar to matlab and Python..

.. with some differences, of course! Otherwise, where would the fun be? ;)

# Installing R

## The main location - CRAN

- The [Comprehensive R Archive Network](https://cran.r-project.org/) or CRAN is where to go for all official things `R`

- To install, select your OS from the main page

## A note for Linux users

- Often, the version on your distribution is not the most up to date

- Instructions are on CRAN about setting things up so you have the latest version. For instance,

  - [Debian](https://cran.r-project.org/bin/linux/debian/#secure-apt)
  - [Ubuntu](https://cran.r-project.org/bin/linux/ubuntu/)

## Development environments

- Terminal version, not very friendly
- Nicer terminal: [radian](https://github.com/randy3k/radian)
- Execute R scripts by using `Rscript name_of_script.R`. Useful to run code in `cron`, for instance
- Integrate into jupyter notebooks
- Use IDEs:
    - [RStudio](https://posit.co/download/rstudio-desktop/) has become the reference; see [Vignette 02](https://julien-arino.github.io/R-for-modellers/SLIDES/vignette-02-Rstudio-and-friends.html)
    - [RKWard](https://rkward.kde.org/) is useful if you are for instance using an ARM processor (Raspberry Pi, some Chromebooks..)

# Running an R script from the command line


## [Why run from the command line?]{.r-fit-text}

- `R` is a scripted language and when run from an `R` console, it is interactive

- $\implies$ what you did before is in memory of the session you are working in

- This is frequent cause for errors when sharing your code with others: some things are defined in your script, others you did in the session but did not copy to the script

## Different program options

When you install `R`, you install several programs

- The executable file, which launches the interactive session
  - In Windows, you get a shortcut to a console version
- A program called `Rscript` that allows you to run an .. `R` script from your OS' command line

## [Run a script from the command line]{.r-fit-text}

```{.bash}
Rscript script/path/script-file-name.R
```
or, from within the directory
```{.bash}
Rscript script-file-name.R
```

## No output by default

- Contrary to the interactive version, if you want to see an output when running from the command line, you have to force it using commands like `print` or `writeLines`

- Figures will also not be displayed, so you may want to save them